version: "3.9"
   
services:
  worker:
    build: .
    command: [celery, --app=tasks.worker_Python.app, worker, --concurrency=20, --loglevel=INFO]
    image: worker 
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq
      - RESULT_BACKEND=rpc
      - NODE_NAME=worker_Python
    restart: 'no'
    volumes:
      - ../:/code
