version: "3.9"
   
services:
  worker:
    build: .
    command: [celery, --app=tasks.worker_Python.app, worker, --concurrency=20, --loglevel=INFO]
    image: worker 
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_IMPORTS=['tasks_Python', 'tasks_Matlab']
      - RESULT_BACKEND=rpc
    depends_on:
      - rabbitmq
    restart: 'no'
    volumes:
      - ../:/code 


  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672